### ISSUE TITLE
Interactive demo CORS failure

### ISSUE THREAD

**Issue by kjkent** [Platane/snk#121]
The interactive demo pulls in the user's profile picture, but then fails with `error :(` on the page and this in the console:
```console
Access to fetch at 'https://snk-one.vercel.app/api/github-user-contribution/kjkent' from origin 'https://platane.me' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://platane.github.io' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
6813e0ec53a4391ce255.js:1247 

GET https://snk-one.vercel.app/api/github-user-contribution/kjkent net::ERR_FAILED 200 (OK)
    onSubmit @ 6813e0ec53a4391ce255.js:1247
    (anonymous) @ 6813e0ec53a4391ce255.js:1057
6813e0ec53a4391ce255.js:1247 
        
Uncaught (in promise) TypeError: Failed to fetch
    at onSubmit (6813e0ec53a4391ce255.js:1247:23)
    at HTMLFormElement.<anonymous> (6813e0ec53a4391ce255.js:1057:9)
```

**Comment by Platane** [comment]
there was a CORS error indeed, I just fixed it
thanks !
